### PR TITLE
Dev.helenn

### PR DESCRIPTION
**Pull request by HelenUnger**
added content boxes, made them responsive

### CODE REVIEW

**Review by cangelozzi — APPROVED** [review]
Code is ok, going through some repo conflicts before merging updates.

**Review by cangelozzi — APPROVED** [review]
Good.

**Comment by cangelozzi** [comment]
Helen, pull it from the master, then try to do the updates.  Folder structure is now updated in master branch.

**Comment by HelenUnger** [comment]
closed due to conflicts

**Pull request closed without merging**
